### PR TITLE
Implement 'page-fieldtype-cleanup' command

### PR DESCRIPTION
**Pull request by barw4**
`page-fieldtype-cleanup` command will search for orphaned `ezpage_*` records and delete them if needed.

### CODE REVIEW

**Review by mateuszbieniek — CHANGES_REQUESTED** [review]
Please update `README.md` accordingly.

**Comment by barw4** [comment]
> Please update `README.md` accordingly.

Resolved in: https://github.com/mateuszbieniek/ezplatform-database-health-checker/pull/3/commits/31c99906802e4021afbf3b748b977d0f1dc64bf9

**Comment by mateuszbieniek** [comment]
Looks ok, but please add information, that this command is only for Enterprise users.

**Review by mateuszbieniek — APPROVED** [review]

**Review by tomaszszopinski — APPROVED** [review]
QA approved on eZPlatform 3.1.5-dev & 3.2.3-dev with diff & patch.

**Pull request merged**
